version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "makeupbox"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1h6ptpir2k1lz"
s3_prefix = "makeupbox"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

