AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  makeupbox - User, subscriber
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        USERS_TABLE: user
        USERS_INDEX: user-id-index
        PURCHASES_TABLE: Purchases
        PURCHASES_INDEX: purchases-userId-index
        INTERACTION_TABLE: interaction-history
        TOOLS_TABLE: tools
        TOOLS_INDEX: tools-id-index
        AIRTABLE_API_KEY: keyLQDq3kyAzazhAK

Resources:
  makeupboxFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        user:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user/getUserById
            Method: get
        subscriber:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user/checkSubscriberById
            Method: get
        updateSubscriber:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user/updateSubscriber
            Method: post
        getPurchases:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user/getPurchases
            Method: get
        addNewUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user/addNewUser
            Method: post
        getUserTools:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user/getUserTools
            Method: get
        addNewUserTool:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user/addNewUserTool
            Method: post
        addSkinTone:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user/addSkinTone
            Method: post
        addEyeShape:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user/addEyeShape
            Method: post
        updateUsageCount:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user/updateUsageCount
            Method: post    
        userlogin:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user/userLogin
            Method: post
        addNewInteraction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /interaction/addNewInteraction
            Method: post
  makeupboxFunctionPurchases:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        addNewPurchase:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /purchases/addNewPurchase
            Method: post    
            
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  makeupboxApi:
    Description: "API Gateway endpoint URL for Prod stage for makeupbox function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/makeupbox/"
  makeupboxFunction:
    Description: "makeupbox Lambda Function ARN"
    Value: !GetAtt makeupboxFunction.Arn
  makeupboxFunctionIamRole:
    Description: "Implicit IAM Role created for makeupbox function"
    Value: !GetAtt makeupboxFunctionRole.Arn
  makeupboxPurchasesApi:
    Description: "API Gateway endpoint URL for Prod stage for makeupbox function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/makeupbox/"
  makeupboxFunctionPurchases:
    Description: "makeupbox Lambda Function ARN"
    Value: !GetAtt makeupboxFunctionPurchases.Arn
  makeupboxFunctionPurchasesIamRole:
    Description: "Implicit IAM Role created for makeupbox function"
    Value: !GetAtt makeupboxFunctionPurchasesRole.Arn